In [1]:
### Name: Arsalan Ahmed
#### Roll No: 21I-0271
#### ML MID EXAM

Importing Libraries

In [22]:
import numpy as np
import pandas as pd
from statistics import mean

Making the Dataset

In [17]:
HeightCol=[6,5.92,5.58,5.92,5,5.5,5.42,5.75]
WeightCol=[180,190,170,165,100,150,130,150]
Footsize=[12,11,12,10,6,8,7,9]
Labels=["M","M","M","M","F","F","F","F"]
columns={"Height":HeightCol,"Weight":WeightCol,"Foot size":Footsize,"Gender":Labels}

In [18]:
df=pd.DataFrame(columns)

In [19]:
df

Height  Weight  Foot size Gender
0    6.00     180         12      M
1    5.92     190         11      M
2    5.58     170         12      M
3    5.92     165         10      M
4    5.00     100          6      F
5    5.50     150          8      F
6    5.42     130          7      F
7    5.75     150          9      F

In [20]:
Test_Sample=[6,130,8]

In [21]:
Pc1=0.5
Pc2=0.5

In [26]:
Male=df[df['Gender']=="M"]
Female=df[df['Gender']=="F"]

In [27]:
Male

Height  Weight  Foot size Gender
0    6.00     180         12      M
1    5.92     190         11      M
2    5.58     170         12      M
3    5.92     165         10      M

In [28]:
Female

Height  Weight  Foot size Gender
4    5.00     100          6      F
5    5.50     150          8      F
6    5.42     130          7      F
7    5.75     150          9      F

Making Mean Vectors

In [29]:
MeanVmale=Male.mean()

<ipython-input-29-f86276c6b303>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  MeanVmale=Male.mean()


In [30]:
MeanVfemale=Female.mean()

<ipython-input-30-a8db29c67c1e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  MeanVfemale=Female.mean()


In [31]:
MeanVmale

Height         5.855
Weight       176.250
Foot size     11.250
dtype: float64

In [33]:
MeanVfemale

Height         5.4175
Weight       132.5000
Foot size      7.5000
dtype: float64

In [119]:
MaleC=list([Male['Height'][:],Male['Weight'][:],Male['Foot size'][:]])

In [120]:
dataMale=np.array([MaleC[0],MaleC[1],MaleC[2]])

In [49]:
dataMale

array([[  6.  ,   5.92,   5.58,   5.92],
       [180.  , 190.  , 170.  , 165.  ],
       [ 12.  ,  11.  ,  12.  ,  10.  ]])

Finding Covariance for both Male and Female

In [54]:
cov_Male=np.cov(dataMale,bias=True)

In [55]:
cov_Male

array([[ 2.62750e-02,  6.06250e-01, -4.87500e-02],
       [ 6.06250e-01,  9.21875e+01,  2.18750e+00],
       [-4.87500e-02,  2.18750e+00,  6.87500e-01]])

In [60]:
cov_Male[2][2]

0.6875

In [56]:
FemaleC=list([Female['Height'][:],Female['Weight'][:],Female['Foot size'][:]])

In [57]:
dataFemale=np.array([FemaleC[0],FemaleC[1],FemaleC[2]])

In [121]:
cov_Female=np.cov(dataFemale,bias=True)

In [59]:
cov_Female

array([[7.291875e-02, 5.206250e+00, 2.912500e-01],
       [5.206250e+00, 4.187500e+02, 2.125000e+01],
       [2.912500e-01, 2.125000e+01, 1.250000e+00]])

In [63]:
for x in range(3):
  for y in range(3):
    if x!=y:
      cov_Male[x][y]=0
      cov_Female[x][y]=0

In [64]:
cov_Male #Covariance Matrix for Male

array([[2.62750e-02, 0.00000e+00, 0.00000e+00],
       [0.00000e+00, 9.21875e+01, 0.00000e+00],
       [0.00000e+00, 0.00000e+00, 6.87500e-01]])

In [65]:
cov_Female #Covariance Matrix for Female

array([[7.291875e-02, 0.000000e+00, 0.000000e+00],
       [0.000000e+00, 4.187500e+02, 0.000000e+00],
       [0.000000e+00, 0.000000e+00, 1.250000e+00]])

Finding the Probabilities for both Male and Female

In [66]:
Test_Sample

[6, 130, 8]

In [67]:
MeanVmale

Height         5.855
Weight       176.250
Foot size     11.250
dtype: float64

In [100]:
M=Test_Sample-MeanVmale

In [80]:
M

Height        0.145
Weight      -46.250
Foot size    -3.250
dtype: float64

In [122]:
d=M.transpose()

In [82]:
d=-1/2*(M)

In [83]:
M

Height        0.145
Weight      -46.250
Foot size    -3.250
dtype: float64

In [85]:
d

Height       -0.0725
Weight       23.1250
Foot size     1.6250
dtype: float64

In [84]:
calM=(1/np.sqrt((2*np.pi*np.linalg.det(cov_Male))))

In [78]:
calM

0.30914792324117585

In [87]:
cal2M=np.linalg.inv(cov_Male)

In [88]:
cal2M

array([[3.80589914e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.08474576e-02, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.45454545e+00]])

P(X|C1)

In [124]:
maleResult=calM*np.exp(np.array(d)@np.array(cal2M)@np.array(M))

In [103]:
maleResult #Male Probability

8.743471300176305e-10

In [101]:
F=Test_Sample-MeanVfemale

In [107]:
c=(-0.5)*F.transpose()

In [108]:
F

Height       0.5825
Weight      -2.5000
Foot size    0.5000
dtype: float64

In [109]:
c

Height      -0.29125
Weight       1.25000
Foot size   -0.25000
dtype: float64

In [123]:
calF=(1/np.sqrt((2*np.pi*np.linalg.det(cov_Female))))

In [111]:
calF

0.06457405238593206

In [112]:
cal2F=np.linalg.inv(cov_Female)

In [113]:
cal2F

array([[1.37138939e+01, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 2.38805970e-03, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.00000000e-01]])

P(X|C2)

In [125]:
femaleResult=calF*np.exp(np.array(c)@np.array(cal2F)@np.array(F))

In [115]:
femaleResult #Female Probability

0.005661817895149121

Positive or Negative Class Categorization

In [117]:
print("C1|X: ",maleResult*Pc1)
print("C1|X: ",femaleResult*Pc2)

C1|X:  4.371735650088153e-10
C1|X:  0.0028309089475745605


In [118]:
m=maleResult*Pc1
f=femaleResult*Pc2
if(m>f):
  print("Test Data is Male")
else:
  print("Test Data is Female")

Test Data is Female


In [ ]:
#Proper Markdowns of the Cells are also done

In [131]:
class NB:
  def __init__(self,data):
    self.dataF=pd.DataFrame(data)
    self.meanvecM=None
    self.meanvecF=None
    self.covM=None
    self.covF=None

  def calculateClass(self):
    Male=self.dataF[self.dataF['Gender']=="M"]
    Female=self.dataF[self.dataF['Gender']=="F"]
    self.meanvecM=Male.mean()
    self.meanvecF=Female.mean()
    MaleC=list([Male['Height'][:],Male['Weight'][:],Male['Foot size'][:]])
    FemaleC=list([Female['Height'][:],Female['Weight'][:],Female['Foot size'][:]])
    dataMale=np.array([MaleC[0],MaleC[1],MaleC[2]])
    dataFemale=np.array([FemaleC[0],FemaleC[1],FemaleC[2]])
    covM=np.cov(dataMale,bias=True)
    covF=np.cov(dataFemale,bias=True)
    for x in range(3):
      for y in range(3):
        if x!=y:
          covM[x][y]=0
          covF[x][y]=0
    def probs(self,test):
      test=(6,130,8)
      M=test-self.meanvecM
      F=test-self.meanvecF
      d=M.transpose()
      c=F.transpose()
      calM=(1/np.sqrt((2*np.pi*np.linalg.det(covM))))
      calF=(1/np.sqrt((2*np.pi*np.linalg.det(covF))))
      cal2F=np.linalg.inv(covF)
      cal2M=np.linalg.inv(covM)
      maleResult=calM*np.exp(np.array(d)@np.array(cal2M)@np.array(M))
      femaleResult=calF*np.exp(np.array(c)@np.array(cal2F)@np.array(F))
    def classification(self):
      m=maleResult*Pc1
      f=femaleResult*Pc2
      if(m>f):
        print("Test Data is Male")
      else:
        print("Test Data is Female")

In [137]:
model=NB()
model.calculateClass()
model.probs(Test_Sample)
model.classification()

Test Data is Male
